heat_template_version: 2016-04-08

description: |
 A resilient, and Highly Available data storage solution backed by Cloud Block 
 Storage, and powered by GlusterFS!

parameter_groups:

- label: Server Settings
  parameters:
  - nodecount
  - nodesize
  - nodeflavour
  - nodeimage

parameters:
  nodecount:
    label: Number of Servers
    description: Number of GlusterFS nodes to create
    type: number
    default: 3
    constraints:
      - range: { min: 2, max: 10 }

  nodesize:
    label: Size of Disk
    description: Size of CBS to boot from
    type: number
    default: 100
    constraints:
      - range: { min: 50, max: 1024 }

  nodeflavour:
    label: Server Size
    description: |
      The size is based on the amount of RAM for the provisioned server.
    type: string
    default: 2 GB General Purpose v1
    constraints:
      - allowed_values:
        - 2 GB General Purpose v1
        - 4 GB General Purpose v1
        - 8 GB General Purpose v1
        - 3.75 GB Compute v1
        - 7.5 GB Compute v1
        - 15 GB Compute v1
        - 30 GB Compute v1
        - 60 GB Compute v1
        - 15 GB I/O v1
        - 30 GB I/O v1
        - 60 GB I/O v1
        - 90 GB I/O v1
        - 120 GB I/O v1
        - 15 GB Memory v1
        - 30 GB Memory v1
        - 60 GB Memory v1
        - 120 GB Memory v1
        - 240 GB Memory v1
        description: must be a valid Nova Cloud Server flavor.

  nodeimage:
    label: Operating System
    description: |
      Server image used for all servers that are created as a part of this
      deployment
    type: string
    default: "CentOS 7 (PVHVM) (Orchestration)"
    constraints:
    - allowed_values:
      - "CentOS 7 (PVHVM) (Orchestration)"
      - "Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM) (Orchestration)"

resources:
  private_net:
    type: "OS::Neutron::Net"
    properties:
      name: "Storage Network"

  private_subnet:
    type: "OS::Neutron::Subnet"
    properties:
      network_id: { get_resource: private_net }
      cidr: "192.168.134.0/24"
      allocation_pools:
        - start: "192.168.134.1"
          end: "192.168.134.254"

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  multi-bfv:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: nodecount } 
      resource_def:
        type: OS::Nova::Server
        properties:
          name: glusternode-%index%
          flavor: { get_param: nodeflavour }
          key_name: { get_resource: ssh_key }
          networks:
            - network: 00000000-0000-0000-0000-000000000000
            - network: 11111111-1111-1111-1111-111111111111
            - network: { get_resource: private_net }
          block_device_mapping_v2:
            - device_name: vda
              delete_on_termination: true
              image: { get_param: nodeimage }
              volume_size: { get_param: nodesize }

outputs:
  private_key:
    description: "SSH Private Key"
    value: { get_attr: [ssh_key, private_key]}

  server_public_ips:
    value: { get_attr: [multi-bfv, accessIPv4] }
    description: "Server IPs"
